name: Run on workflows
on:
    push:
      branches: [ main ]
    workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancelling duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - uses: actions/setup-node@v2
         with:
            node-version: '16'
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9
       - name: cloning repo and install
         continue-on-error: true
         run: |
            apt -qq update && apt -qq install -y --no-install-recommends git ffmpeg aria2c
            git clone https://${{ secrets.TOKEN }}@github.com/Bainshedone/auto-encode-test test && cd test && pip3 install -r requirements.txt
       - name: cloning current repo
         continue-on-error:  true
         run: |
            git clone https://${{ secrets.TOKEN }}@github.com/Bainshedone/test101 app 
            cd app && sudo mv link.py /auto-encode-test/test
       - name: Running
         timeout-minutes: 350
         continue-on-error: true
         run: |
           aria2c --daemon=true --enable-rpc=true -j5 -x5 && cd test && python3 ariatest.py
